name: mh-ai
channels:
  - pytorch
  - defaults
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.01.04=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - contourpy=1.3.1=py310h214f63a_0
  - cpuonly=2.0=0
  - cycler=0.12.1=py310haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.3=py310haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py310h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=12.3.0=h3ef6528_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.3=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h652a1e2_0
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.6.0=h55ef9bb_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.8=py310haa95532_0
  - matplotlib-base=3.10.8=py310h26e45b9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numexpr=2.11.0=py310hdb065b2_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=12.1.0=py310h6b7a805_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pycparser=2.23=py310haa95532_0
  - pyparsing=3.2.5=py310haa95532_0
  - pyqt=6.7.1=py310h378bd72_2
  - pyqt6-sip=13.9.1=py310h02ab6af_2
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py310haa95532_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - requests=2.32.5=py310haa95532_1
  - scikit-learn=1.7.2=py310h7f7e138_1
  - scipy=1.15.3=py310h180bac5_0
  - setuptools=80.10.1=py310haa95532_0
  - sip=6.10.0=py310h5da7b33_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - sympy=1.14.0=py310haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - tbb-devel=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py310h4442805_1
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=py310haa95532_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - tornado=6.5.4=py310h02ab6af_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py310haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - colorama==0.4.6
      - datasets==2.18.0
      - decorator==5.2.1
      - dill==0.3.8
      - frozenlist==1.8.0
      - fsspec==2024.2.0
      - huggingface-hub==0.20.3
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - multiprocess==0.70.16
      - numba==0.63.1
      - numpy==2.2.6
      - opencv-python==4.13.0.90
      - platformdirs==4.5.1
      - pooch==1.8.2
      - propcache==0.4.1
      - pyarrow==23.0.0
      - pyarrow-hotfix==0.7
      - regex==2026.1.15
      - safetensors==0.7.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - tokenizers==0.15.2
      - tqdm==4.67.1
      - transformers==4.36.2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\DELL\miniconda3\envs\mh-ai
